---
- block:
  - name: Copy template of timer units
    template:
      src: restic.timer.j2
      dest: /etc/systemd/system/{{ item.name }}.timer
#      validate: systemd-analyze verify %s
      force: true
      backup: true
    with_items: "{{ restic_auto_backup_jobs }}"

  - name: Copy template of service units
    template:
      src: restic.service.j2
      dest: /etc/systemd/system/{{ item.name }}.service
#      validate: systemd-analyze verify %s
      force: true
      backup: true
    with_items: "{{ restic_auto_backup_jobs }}"

  - name: Start and enable timer units
    systemd:
      name: "{{ item.name }}.timer"
      state: started
      enabled: true
      daemon_reload: true
    with_items: "{{ restic_auto_backup_jobs }}"
  become: true

# not happy with directly putting access keys in unit files
# with nested on templates?
# FAQ about not needing to start/enable both service and timer
# add service that restic check --read-data
# add tags and hostname and exclusion and connection options support

# validation is broken by Ansible
# https://github.com/ansible/ansible/issues/19232
