---
- block:
  - name: Install necessary packages on Fedora
    dnf:
      name: "{{ restic_auto_backup_Fedora_packages }}"
      state: present

  - name: Download restic COPR repository on Fedora
    get_url:
      url: "https://copr.fedorainfracloud.org/coprs/copart/restic/repo/fedora-{{ ansible_distribution_major_version }}/copart-restic-fedora-{{ ansible_distribution_major_version }}.repo"
      dest: "/etc/yum.repos.d/{{ restic_auto_backup_copr_name }}"

  - name: Install restic package on Fedora
    dnf:
      name: restic
      state: present
  become: true
